const fs = require('fs');

const extracted = JSON.parse(fs.readFileSync('extracted.json', 'utf-8'));

const descriptions = {
  "Two Sum": "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
  "Best Time to Buy and Sell Stock": "You are given an array prices where prices[i] is the price of a given stock on the ith day. Return the maximum profit you can achieve from this transaction.",
  "Contains Duplicate": "Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.",
  "Product of Array Except Self": "Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].",
  "Maximum Subarray": "Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.",
  "Maximum Product Subarray": "Given an integer array nums, find a contiguous non-empty subarray within the array that has the largest product, and return the product.",
  "Find Minimum in Rotated Sorted Array": "Suppose an array of length n sorted in ascending order is rotated between 1 and n times. Given the sorted rotated array nums of unique elements, return the minimum element of this array.",
  "Search in Rotated Sorted Array": "Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.",
  "3Sum": "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.",
  "Container With Most Water": "You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container, such that the container contains the most water.",
  "Sum of Two Integers": "Given two integers a and b, return the sum of the two integers without using the operators + and -.",
  "Number of 1 Bits": "Write a function that takes an unsigned integer and returns the number of '1' bits it has (also known as the Hamming weight).",
  "Counting Bits": "Given an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1's in the binary representation of i.",
  "Missing Number": "Given an array nums containing n distinct numbers in the range [0, n], return the only number in the range that is missing from the array.",
  "Reverse Bits": "Reverse bits of a given 32 bits unsigned integer.",
  "Climbing Stairs": "You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
  "Coin Change": "You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money. Return the fewest number of coins that you need to make up that amount.",
  "Longest Increasing Subsequence": "Given an integer array nums, return the length of the longest strictly increasing subsequence.",
  "Longest Common Subsequence": "Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.",
  "Word Break": "Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.",
  "Combination Sum": "Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target.",
  "House Robber": "You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night.",
  "House Robber II": "You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. All houses at this place are arranged in a circle. That means the first house is the neighbor of the last one.",
  "Decode Ways": "A message containing letters from A-Z can be encoded into numbers using the following mapping: 'A' -> \"1\", 'B' -> \"2\", ... 'Z' -> \"26\". Given a string s containing only digits, return the number of ways to decode it.",
  "Unique Paths": "There is a robot on an m x n grid. The robot is initially located at the top-left corner (i.e., grid[0][0]). The robot tries to move to the bottom-right corner (i.e., grid[m - 1][n - 1]). The robot can only move either down or right at any point in time.",
  "Jump Game": "You are given an integer array nums. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position. Return true if you can reach the last index, or false otherwise.",
  "Clone Graph": "Given a reference of a node in a connected undirected graph. Return a deep copy (clone) of the graph.",
  "Course Schedule": "There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai. Return true if you can finish all courses. Otherwise, return false.",
  "Pacific Atlantic Water Flow": "There is an m x n rectangular island that borders both the Pacific Ocean and Atlantic Ocean. The Pacific Ocean touches the island's left and top edges, and the Atlantic Ocean touches the island's right and bottom edges. Return a list of grid coordinates result where result[i] = [ri, ci] denotes that rain water can flow from cell (ri, ci) to both the Pacific and Atlantic oceans.",
  "Number of Islands": "Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.",
  "Longest Consecutive Sequence": "Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence. You must write an algorithm that runs in O(n) time.",
  "Alien Dictionary": "There is a new alien language that uses the English alphabet. However, the order among the letters is unknown to you. You are given a list of strings words from the alien language's dictionary, where the strings in words are sorted lexicographically by the rules of this new language. Return a string of the unique letters in the new alien language sorted in lexicographically increasing order by the new language's rules.",
  "Graph Valid Tree": "You have a graph of n nodes labeled from 0 to n - 1. You are given an integer n and a list of edges where edges[i] = [ai, bi] indicates that there is an undirected edge between nodes ai and bi in the graph. Return true if the edges of the given graph make up a valid tree, and false otherwise.",
  "Number of Connected Components in an Undirected Graph": "You have a graph of n nodes. You are given an integer n and an array edges where edges[i] = [ai, bi] indicates that there is an edge between ai and bi in the graph. Return the number of connected components in the graph.",
  "Insert Interval": "You are given an array of non-overlapping intervals intervals where intervals[i] = [starti, endi] represent the start and the end of the ith interval and intervals is sorted in ascending order by starti. You are also given an interval newInterval = [start, end] that represents the start and end of another interval. Insert newInterval into intervals such that intervals is still sorted in ascending order by starti and intervals still does not have any overlapping intervals (merge overlapping intervals if necessary).",
  "Merge Intervals": "Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.",
  "Non-overlapping Intervals": "Given an array of intervals intervals where intervals[i] = [starti, endi], return the minimum number of intervals you need to remove to make the rest of the intervals non-overlapping.",
  "Meeting Rooms": "Given an array of meeting time intervals where intervals[i] = [starti, endi], determine if a person could attend all meetings.",
  "Meeting Rooms II": "Given an array of meeting time intervals intervals where intervals[i] = [starti, endi], return the minimum number of conference rooms required.",
  "Reverse Linked List": "Given the head of a singly linked list, reverse the list, and return the reversed list.",
  "Linked List Cycle": "Given head, the head of a linked list, determine if the linked list has a cycle in it.",
  "Merge Two Sorted Lists": "You are given the heads of two sorted linked lists list1 and list2. Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.",
  "Merge k Sorted Lists": "You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.",
  "Remove Nth Node From End of List": "Given the head of a linked list, remove the nth node from the end of the list and return its head.",
  "Reorder List": "You are given the head of a singly linked-list. The list can be represented as: L0 → L1 → … → Ln - 1 → Ln. Reorder the list to be on the following form: L0 → Ln → L1 → Ln - 1 → L2 → Ln - 2 → …",
  "Set Matrix Zeroes": "Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0's. You must do it in place.",
  "Spiral Matrix": "Given an m x n matrix, return all elements of the matrix in spiral order.",
  "Rotate Image": "You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise). You have to rotate the image in-place, which means you have to modify the input 2D matrix directly.",
  "Word Search": "Given an m x n grid of characters board and a string word, return true if word exists in the grid. The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring.",
  "Longest Substring Without Repeating Characters": "Given a string s, find the length of the longest substring without repeating characters.",
  "Longest Repeating Character Replacement": "You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most k times. Return the length of the longest substring containing the same letter you can get after performing the above operations.",
  "Minimum Window Substring": "Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string \"\".",
  "Valid Anagram": "Given two strings s and t, return true if t is an anagram of s, and false otherwise.",
  "Group Anagrams": "Given an array of strings strs, group the anagrams together. You can return the answer in any order.",
  "Valid Parentheses": "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
  "Valid Palindrome": "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers. Given a string s, return true if it is a palindrome, or false otherwise.",
  "Longest Palindromic Substring": "Given a string s, return the longest palindromic substring in s.",
  "Palindromic Substrings": "Given a string s, return the number of palindromic substrings in it. A string is a palindrome when it reads the same backward as forward. A substring is a contiguous sequence of characters within the string.",
  "Encode and Decode Strings": "Design an algorithm to encode a list of strings to a string. The encoded string is then sent over the network and is decoded back to the original list of strings.",
  "Maximum Depth of Binary Tree": "Given the root of a binary tree, return its maximum depth. A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.",
  "Same Tree": "Given the roots of two binary trees p and q, write a function to check if they are the same or not. Two binary trees are considered the same if they are structurally identical, and the nodes have the same value.",
  "Invert Binary Tree": "Given the root of a binary tree, invert the tree, and return its root.",
  "Binary Tree Maximum Path Sum": "A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once. Note that the path does not need to pass through the root. The path sum of a path is the sum of the node's values in the path. Given the root of a binary tree, return the maximum path sum of any non-empty path.",
  "Binary Tree Level Order Traversal": "Given the root of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).",
  "Subtree of Another Tree": "Given the roots of two binary trees root and subRoot, return true if there is a subtree of root with the same structure and node values of subRoot and false otherwise.",
  "Construct Binary Tree from Preorder and Inorder Traversal": "Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.",
  "Validate Binary Search Tree": "Given the root of a binary tree, determine if it is a valid binary search tree (BST).",
  "Kth Smallest Element in a BST": "Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.",
  "Lowest Common Ancestor of a BST": "Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.",
  "Implement Trie (Prefix Tree)": "A trie (pronounced as \"try\") or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings. There are various applications of this very efficient data structure, such as autocomplete and spellchecker. Implement the Trie class.",
  "Top K Frequent Elements": "Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.",
  "Find Median from Data Stream": "The median is the middle value in an ordered integer list. If the size of the list is even, there is no middle value, and the median is the mean of the two middle values. Implement the MedianFinder class.",
  "Koko Eating Bananas": "Koko loves to eat bananas. There are n piles of bananas, the ith pile has piles[i] bananas. The guards have gone and will come back in h hours. Koko can decide her bananas-per-hour eating speed of k. Each hour, she chooses some pile of bananas and eats k bananas from that pile. If the pile has less than k bananas, she eats all of them instead and will not eat any more bananas during this hour. Return the minimum integer k such that she can eat all the bananas within h hours.",
  "Search a 2D Matrix": "You are given an m x n integer matrix matrix with the following two properties: Each row is sorted in non-decreasing order. The first integer of each row is greater than the last integer of the previous row. Given an integer target, return true if target is in matrix or false otherwise.",
  "Time Based Key-Value Store": "Design a time-based key-value data structure that can store multiple values for the same key at different time stamps and retrieve the key's value at a certain timestamp. Implement the TimeMap class.",
  "Min Stack": "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time. Implement the MinStack class.",
  "Evaluate Reverse Polish Notation": "You are given an array of strings tokens that represents an arithmetic expression in a Reverse Polish Notation. Evaluate the expression. Return an integer that represents the value of the expression.",
  "Generate Parentheses": "Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.",
  "Daily Temperatures": "Given an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the ith day to get a warmer temperature. If there is no future day for which this is possible, keep answer[i] == 0 instead.",
  "Car Fleet": "There are n cars going to the same destination along a one-lane road. The destination is target miles away. You are given two integer array position and speed, both of length n, where position[i] is the position of the ith car and speed[i] is the speed of the ith car (in miles per hour). Return the number of car fleets that will arrive at the destination.",
  "Largest Rectangle in Histogram": "Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
  "Design Twitter": "Design a simplified version of Twitter where users can post tweets, follow/unfollow another user, and is able to see the 10 most recent tweets in the user's news feed. Implement the Twitter class.",
  "K Closest Points to Origin": "Given an array of points where points[i] = [xi, yi] represents a point on the X-Y plane and an integer k, return the k closest points to the origin (0, 0).",
  "Last Stone Weight": "You are given an array of integers stones where stones[i] is the weight of the ith stone. We are playing a game with the stones. On each turn, we choose the heaviest two stones and smash them together. Return the weight of the last remaining stone. If there are no stones left, return 0."
};

for (const key in extracted) {
  extracted[key].description = descriptions[key] || "Description for " + key;
}

fs.writeFileSync('chunk1.json', JSON.stringify(extracted, null, 2));
console.log('Added descriptions to chunk1.json');
