const fs = require('fs');

const missingProblems = {
  "Serialize and Deserialize Binary Tree": {
    description: "Serialization is the process of converting a data structure or object into a sequence of bits so that it can be stored in a file or memory buffer, or transmitted across a network connection link to be reconstructed later in the same or another computer environment. Design an algorithm to serialize and deserialize a binary tree.",
    explanation: "Use BFS (Level Order Traversal) or DFS (Preorder Traversal) to serialize the tree into a string. Use a delimiter like ',' to separate node values and a special character like 'N' for null nodes. For deserialization, split the string and reconstruct the tree using the same traversal.",
    implementation: "class Codec:\n    def serialize(self, root):\n        res = []\n        def dfs(node):\n            if not node:\n                res.append('N')\n                return\n            res.append(str(node.val))\n            dfs(node.left)\n            dfs(node.right)\n        dfs(root)\n        return ','.join(res)\n\n    def deserialize(self, data):\n        vals = data.split(',')\n        self.i = 0\n        def dfs():\n            if vals[self.i] == 'N':\n                self.i += 1\n                return None\n            node = TreeNode(int(vals[self.i]))\n            self.i += 1\n            node.left = dfs()\n            node.right = dfs()\n            return node\n        return dfs()"
  },
  "Add and Search Word": {
    description: "Design a data structure that supports adding new words and finding if a string matches any previously added string. The string can contain dots '.' where dots can be matched with any letter.",
    explanation: "Use a Trie (Prefix Tree). For adding words, insert characters node by node. For searching, use DFS. If the character is '.', recursively check all children of the current Trie node.",
    implementation: "class WordDictionary:\n    def __init__(self):\n        self.trie = {}\n\n    def addWord(self, word: str) -> None:\n        node = self.trie\n        for c in word:\n            if c not in node:\n                node[c] = {}\n            node = node[c]\n        node['$'] = True\n\n    def search(self, word: str) -> bool:\n        def dfs(j, root):\n            cur = root\n            for i in range(j, len(word)):\n                c = word[i]\n                if c == '.':\n                    for child in cur.values():\n                        if child != True and dfs(i + 1, child):\n                            return True\n                    return False\n                else:\n                    if c not in cur:\n                        return False\n                    cur = cur[c]\n            return '$' in cur\n        return dfs(0, self.trie)"
  },
  "Word Search II": {
    description: "Given an m x n board of characters and a list of strings words, return all words on the board. Each word must be constructed from letters of sequentially adjacent cells.",
    explanation: "Combine a Trie with DFS (Backtracking). Insert all words into a Trie. Then, iterate through each cell on the board and perform DFS. If the current character is in the Trie, continue DFS. Mark visited cells to avoid reusing them.",
    implementation: "class Solution:\n    def findWords(self, board: List[List[str]], words: List[str]) -> List[str]:\n        trie = {}\n        for w in words:\n            node = trie\n            for c in w:\n                if c not in node: node[c] = {}\n                node = node[c]\n            node['$'] = w\n        res, visited = set(), set()\n        def dfs(r, c, node):\n            if r < 0 or c < 0 or r >= len(board) or c >= len(board[0]) or (r, c) in visited or board[r][c] not in node:\n                return\n            visited.add((r, c))\n            node = node[board[r][c]]\n            if '$' in node: res.add(node['$'])\n            dfs(r + 1, c, node)\n            dfs(r - 1, c, node)\n            dfs(r, c + 1, node)\n            dfs(r, c - 1, node)\n            visited.remove((r, c))\n        for r in range(len(board)):\n            for c in range(len(board[0])):\n                dfs(r, c, trie)\n        return list(res)"
  },
  "Merge K Sorted Lists": {
    description: "You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.",
    explanation: "Use a Min-Heap (Priority Queue). Push the head of each linked list into the heap. Extract the minimum node, add it to the result list, and push its next node into the heap. Repeat until the heap is empty.",
    implementation: "class Solution:\n    def mergeKLists(self, lists: List[Optional[ListNode]]) -> Optional[ListNode]:\n        import heapq\n        heap = []\n        for i, l in enumerate(lists):\n            if l: heapq.heappush(heap, (l.val, i, l))\n        dummy = ListNode()\n        curr = dummy\n        while heap:\n            val, i, node = heapq.heappop(heap)\n            curr.next = node\n            curr = curr.next\n            if node.next:\n                heapq.heappush(heap, (node.next.val, i, node.next))\n        return dummy.next"
  },
  "Find Minimum in Rotated Sorted Array II": {
    description: "Suppose an array of length n sorted in ascending order is rotated between 1 and n times. This array may contain duplicates. Given the sorted rotated array nums, return the minimum element of this array.",
    explanation: "Use binary search. If nums[mid] > nums[right], the minimum is in the right half. If nums[mid] < nums[right], the minimum is in the left half. If they are equal, we can't be sure, so we just decrement the right pointer.",
    implementation: "class Solution:\n    def findMin(self, nums: List[int]) -> int:\n        l, r = 0, len(nums) - 1\n        while l < r:\n            m = l + (r - l) // 2\n            if nums[m] > nums[r]:\n                l = m + 1\n            elif nums[m] < nums[r]:\n                r = m\n            else:\n                r -= 1\n        return nums[l]"
  },
  "Search in Rotated Sorted Array II": {
    description: "There is an integer array nums sorted in non-decreasing order (not necessarily with distinct values). Given the array nums after the rotation and an integer target, return true if target is in nums, or false if it is not in nums.",
    explanation: "Use binary search. Similar to the version without duplicates, but if nums[l] == nums[mid] == nums[r], we can't determine which half is sorted, so we shrink the search space by incrementing l and decrementing r.",
    implementation: "class Solution:\n    def search(self, nums: List[int], target: int) -> bool:\n        l, r = 0, len(nums) - 1\n        while l <= r:\n            m = l + (r - l) // 2\n            if nums[m] == target: return True\n            if nums[l] == nums[m] == nums[r]:\n                l += 1\n                r -= 1\n            elif nums[l] <= nums[m]:\n                if nums[l] <= target < nums[m]: r = m - 1\n                else: l = m + 1\n            else:\n                if nums[m] < target <= nums[r]: l = m + 1\n                else: r = m - 1\n        return False"
  },
  "Median of Two Sorted Arrays": {
    description: "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)).",
    explanation: "Use binary search on the smaller array to find the correct partition. The partition should split both arrays such that the left half has the same number of elements as the right half, and all elements on the left are smaller than all elements on the right.",
    implementation: "class Solution:\n    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:\n        A, B = nums1, nums2\n        if len(A) > len(B): A, B = B, A\n        total = len(A) + len(B)\n        half = total // 2\n        l, r = 0, len(A) - 1\n        while True:\n            i = (l + r) // 2\n            j = half - i - 2\n            Aleft = A[i] if i >= 0 else float('-inf')\n            Aright = A[i + 1] if (i + 1) < len(A) else float('inf')\n            Bleft = B[j] if j >= 0 else float('-inf')\n            Bright = B[j + 1] if (j + 1) < len(B) else float('inf')\n            if Aleft <= Bright and Bleft <= Aright:\n                if total % 2:\n                    return min(Aright, Bright)\n                return (max(Aleft, Bleft) + min(Aright, Bright)) / 2\n            elif Aleft > Bright:\n                r = i - 1\n            else:\n                l = i + 1"
  },
  "Sliding Window Maximum": {
    description: "You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position. Return the max sliding window.",
    explanation: "Use a monotonically decreasing deque to store indices. The front of the deque will always be the index of the maximum element in the current window. Remove indices that are out of the window bounds or smaller than the current element.",
    implementation: "class Solution:\n    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:\n        import collections\n        output = []\n        q = collections.deque()\n        l = r = 0\n        while r < len(nums):\n            while q and nums[q[-1]] < nums[r]:\n                q.pop()\n            q.append(r)\n            if l > q[0]:\n                q.popleft()\n            if (r + 1) >= k:\n                output.append(nums[q[0]])\n                l += 1\n            r += 1\n        return output"
  },
  "Permutation in String": {
    description: "Given two strings s1 and s2, return true if s2 contains a permutation of s1, or false otherwise. In other words, return true if one of s1's permutations is the substring of s2.",
    explanation: "Use a sliding window and two frequency maps (or arrays). Keep a window of size len(s1) on s2. Compare the frequency map of the current window with the frequency map of s1. If they match, return true.",
    implementation: "class Solution:\n    def checkInclusion(self, s1: str, s2: str) -> bool:\n        if len(s1) > len(s2): return False\n        s1Count, s2Count = [0] * 26, [0] * 26\n        for i in range(len(s1)):\n            s1Count[ord(s1[i]) - ord('a')] += 1\n            s2Count[ord(s2[i]) - ord('a')] += 1\n        matches = 0\n        for i in range(26):\n            matches += (1 if s1Count[i] == s2Count[i] else 0)\n        l = 0\n        for r in range(len(s1), len(s2)):\n            if matches == 26: return True\n            index = ord(s2[r]) - ord('a')\n            s2Count[index] += 1\n            if s1Count[index] == s2Count[index]: matches += 1\n            elif s1Count[index] + 1 == s2Count[index]: matches -= 1\n            index = ord(s2[l]) - ord('a')\n            s2Count[index] -= 1\n            if s1Count[index] == s2Count[index]: matches += 1\n            elif s1Count[index] - 1 == s2Count[index]: matches -= 1\n            l += 1\n        return matches == 26"
  },
  "Largest Rectangle in Histogram": {
    description: "Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
    explanation: "Use a monotonic increasing stack to keep track of the indices and heights. If the current height is smaller than the top of the stack, pop from the stack and calculate the area using the popped height and the current index as the width.",
    implementation: "class Solution:\n    def largestRectangleArea(self, heights: List[int]) -> int:\n        maxArea = 0\n        stack = [] # pair: (index, height)\n        for i, h in enumerate(heights):\n            start = i\n            while stack and stack[-1][1] > h:\n                index, height = stack.pop()\n                maxArea = max(maxArea, height * (i - index))\n                start = index\n            stack.append((start, h))\n        for i, h in stack:\n            maxArea = max(maxArea, h * (len(heights) - i))\n        return maxArea"
  },
  "Design Twitter": {
    description: "Design a simplified version of Twitter where users can post tweets, follow/unfollow another user, and is able to see the 10 most recent tweets in the user's news feed.",
    explanation: "Use a hash map to store followers and another hash map to store tweets for each user. To get the news feed, use a Min-Heap (Priority Queue) to merge the most recent tweets from the user and their followees.",
    implementation: "class Twitter:\n    def __init__(self):\n        import collections\n        self.count = 0\n        self.tweetMap = collections.defaultdict(list)\n        self.followMap = collections.defaultdict(set)\n\n    def postTweet(self, userId: int, tweetId: int) -> None:\n        self.tweetMap[userId].append([self.count, tweetId])\n        self.count -= 1\n\n    def getNewsFeed(self, userId: int) -> List[int]:\n        import heapq\n        res = []\n        minHeap = []\n        self.followMap[userId].add(userId)\n        for followeeId in self.followMap[userId]:\n            if followeeId in self.tweetMap:\n                index = len(self.tweetMap[followeeId]) - 1\n                count, tweetId = self.tweetMap[followeeId][index]\n                minHeap.append([count, tweetId, followeeId, index - 1])\n        heapq.heapify(minHeap)\n        while minHeap and len(res) < 10:\n            count, tweetId, followeeId, index = heapq.heappop(minHeap)\n            res.append(tweetId)\n            if index >= 0:\n                count, tweetId = self.tweetMap[followeeId][index]\n                heapq.heappush(minHeap, [count, tweetId, followeeId, index - 1])\n        return res\n\n    def follow(self, followerId: int, followeeId: int) -> None:\n        self.followMap[followerId].add(followeeId)\n\n    def unfollow(self, followerId: int, followeeId: int) -> None:\n        if followeeId in self.followMap[followerId]:\n            self.followMap[followerId].remove(followeeId)"
  },
  "K Closest Points to Origin": {
    description: "Given an array of points where points[i] = [xi, yi] represents a point on the X-Y plane and an integer k, return the k closest points to the origin (0, 0).",
    explanation: "Use a Max-Heap of size k. Iterate through the points, calculate the squared distance to the origin, and push it to the heap. If the heap size exceeds k, pop the maximum element. The remaining elements are the k closest points.",
    implementation: "class Solution:\n    def kClosest(self, points: List[List[int]], k: int) -> List[List[int]]:\n        import heapq\n        pts = []\n        for x, y in points:\n            dist = (x ** 2) + (y ** 2)\n            pts.append([dist, x, y])\n        heapq.heapify(pts)\n        res = []\n        for _ in range(k):\n            dist, x, y = heapq.heappop(pts)\n            res.append([x, y])\n        return res"
  },
  "Last Stone Weight": {
    description: "You are given an array of integers stones where stones[i] is the weight of the ith stone. We are playing a game with the stones. On each turn, we choose the heaviest two stones and smash them together.",
    explanation: "Use a Max-Heap (Priority Queue). Since Python only has a Min-Heap, multiply the weights by -1 before pushing them to the heap. Repeatedly pop the two heaviest stones, smash them, and push the difference back if it's not zero.",
    implementation: "class Solution:\n    def lastStoneWeight(self, stones: List[int]) -> int:\n        import heapq\n        stones = [-s for s in stones]\n        heapq.heapify(stones)\n        while len(stones) > 1:\n            first = heapq.heappop(stones)\n            second = heapq.heappop(stones)\n            if second > first:\n                heapq.heappush(stones, first - second)\n        stones.append(0)\n        return abs(stones[0])"
  },
  "Subsets": {
    description: "Given an integer array nums of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets. Return the solution in any order.",
    explanation: "Use backtracking (DFS). For each element, you have two choices: either include it in the current subset or exclude it. Recursively explore both choices to generate all possible subsets.",
    implementation: "class Solution:\n    def subsets(self, nums: List[int]) -> List[List[int]]:\n        res = []\n        subset = []\n        def dfs(i):\n            if i >= len(nums):\n                res.append(subset.copy())\n                return\n            subset.append(nums[i])\n            dfs(i + 1)\n            subset.pop()\n            dfs(i + 1)\n        dfs(0)\n        return res"
  },
  "Combination Sum II": {
    description: "Given a collection of candidate numbers (candidates) and a target number (target), find all unique combinations in candidates where the candidate numbers sum to target. Each number in candidates may only be used once in the combination.",
    explanation: "Sort the candidates first. Use backtracking. To avoid duplicate combinations, skip candidates that are the same as the previous candidate at the same depth of the recursion tree.",
    implementation: "class Solution:\n    def combinationSum2(self, candidates: List[int], target: int) -> List[List[int]]:\n        candidates.sort()\n        res = []\n        def dfs(pos, cur, target):\n            if target == 0:\n                res.append(cur.copy())\n                return\n            if target <= 0:\n                return\n            prev = -1\n            for i in range(pos, len(candidates)):\n                if candidates[i] == prev:\n                    continue\n                cur.append(candidates[i])\n                dfs(i + 1, cur, target - candidates[i])\n                cur.pop()\n                prev = candidates[i]\n        dfs(0, [], target)\n        return res"
  },
  "Permutations": {
    description: "Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.",
    explanation: "Use backtracking. For each position, iterate through the remaining available numbers, add one to the current permutation, and recursively generate the rest. Use a set or boolean array to keep track of used numbers.",
    implementation: "class Solution:\n    def permute(self, nums: List[int]) -> List[List[int]]:\n        res = []\n        if len(nums) == 1:\n            return [nums[:]]\n        for i in range(len(nums)):\n            n = nums.pop(0)\n            perms = self.permute(nums)\n            for perm in perms:\n                perm.append(n)\n            res.extend(perms)\n            nums.append(n)\n        return res"
  },
  "Subsets II": {
    description: "Given an integer array nums that may contain duplicates, return all possible subsets (the power set). The solution set must not contain duplicate subsets. Return the solution in any order.",
    explanation: "Sort the array first. Use backtracking. Similar to Subsets, but to avoid duplicates, when excluding the current element, skip all subsequent identical elements before making the next recursive call.",
    implementation: "class Solution:\n    def subsetsWithDup(self, nums: List[int]) -> List[List[int]]:\n        res = []\n        nums.sort()\n        def dfs(i, subset):\n            if i == len(nums):\n                res.append(subset[::])\n                return\n            subset.append(nums[i])\n            dfs(i + 1, subset)\n            subset.pop()\n            while i + 1 < len(nums) and nums[i] == nums[i + 1]:\n                i += 1\n            dfs(i + 1, subset)\n        dfs(0, [])\n        return res"
  },
  "Palindrome Partitioning": {
    description: "Given a string s, partition s such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of s.",
    explanation: "Use backtracking. Iterate through the string, and for each prefix that is a palindrome, recursively partition the remaining suffix. Combine the valid partitions to form the result.",
    implementation: "class Solution:\n    def partition(self, s: str) -> List[List[str]]:\n        res = []\n        part = []\n        def dfs(i):\n            if i >= len(s):\n                res.append(part.copy())\n                return\n            for j in range(i, len(s)):\n                if self.isPali(s, i, j):\n                    part.append(s[i:j+1])\n                    dfs(j + 1)\n                    part.pop()\n        dfs(0)\n        return res\n    def isPali(self, s, l, r):\n        while l < r:\n            if s[l] != s[r]: return False\n            l, r = l + 1, r - 1\n        return True"
  },
  "Letter Combinations of a Phone Number": {
    description: "Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.",
    explanation: "Use backtracking. Map each digit to its corresponding letters. For each digit in the input string, iterate through its letters, append one to the current combination, and recursively process the next digit.",
    implementation: "class Solution:\n    def letterCombinations(self, digits: str) -> List[str]:\n        res = []\n        digitToChar = { '2': 'abc', '3': 'def', '4': 'ghi', '5': 'jkl', '6': 'mno', '7': 'qprs', '8': 'tuv', '9': 'wxyz' }\n        def dfs(i, curStr):\n            if len(curStr) == len(digits):\n                res.append(curStr)\n                return\n            for c in digitToChar[digits[i]]:\n                dfs(i + 1, curStr + c)\n        if digits:\n            dfs(0, '')\n        return res"
  },
  "N-Queens": {
    description: "The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Given an integer n, return all distinct solutions to the n-queens puzzle.",
    explanation: "Use backtracking. Keep track of the columns, positive diagonals, and negative diagonals that are currently under attack. Try placing a queen in each column of the current row, and recursively move to the next row.",
    implementation: "class Solution:\n    def solveNQueens(self, n: int) -> List[List[str]]:\n        col = set()\n        posDiag = set() # (r + c)\n        negDiag = set() # (r - c)\n        res = []\n        board = [['.'] * n for i in range(n)]\n        def dfs(r):\n            if r == n:\n                copy = [''.join(row) for row in board]\n                res.append(copy)\n                return\n            for c in range(n):\n                if c in col or (r + c) in posDiag or (r - c) in negDiag:\n                    continue\n                col.add(c)\n                posDiag.add(r + c)\n                negDiag.add(r - c)\n                board[r][c] = 'Q'\n                dfs(r + 1)\n                col.remove(c)\n                posDiag.remove(r + c)\n                negDiag.remove(r - c)\n                board[r][c] = '.'\n        dfs(0)\n        return res"
  }
};

fs.writeFileSync('chunk2.json', JSON.stringify(missingProblems, null, 2));
console.log('Created chunk2.json with 20 problems');
